version: '3.8'

services:
  app:
    image: 'thinhvn/backend:1.0.0'
    restart: always
    container_name: backend_name
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    build:
      context: .
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=sakila
      - DB_PORT=3306
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sakila
    ports:
      - 3306:3306
